export type TypeUser = {
  id: number;
  uid: string | null;
  avatar: string | null;
  customerCode: string;
  fullName: string;
  userName: string;
  role: string;
  contactPerson: string;
  email: string | null;
  phone: string | null;
  address: string | null;
  address1: string | null;
  address2: string | null;
  country: string | null;
  state: string | null;
  province: string | null;
  city: string | null;
  regency: string | null;
  subDistrict: string | null;
  village: string | null;
  regionalId: number | null;
  regionalName: string | null;
  branchId: number | null;
  branchName: string | null;
  subBranch: string | null;
  warehouseName: string | null;
  zipCode: string | null;
  latitude: string | null;
  longitude: string | null;
  categorySchedule: string | null;
  visitingSchedule: string | null;
  salesForceCode: string | null;
  salesName: string | null;
  tap: string | null;
  status_pjp: string | null;
  idCardNumber: string | null;
  taxNumber: string | null;
  description: string | null;
  image: string | null;
  status: string | null;
  userId: number | null;
};
